[workspace]
members = [
	"commons/rust",
	"aoc_2022",
	"synacor",
	"1brc_2024"
]
resolver = "2"

[profile.release2]
inherits = "release"
strip = true
lto = true
codegen-units = 1
incremental = false
panic = "abort"
