[package]
name = "obrc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
memchr = "2.7.1"
rustc-hash = "1.1.0"

[profile.release2]
inherits = "release"
strip = true
lto = true
codegen-units = 1
incremental = false
panic = "abort"
